// Mocks generated by Mockito 5.4.4 from annotations
// in ui/test/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ui/data/datasources/remote/product_remote_data_source.dart'
    as _i3;
import 'package:ui/data/models/product_item_model.dart' as _i5;
import 'package:ui/data/models/search_product_item_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i3.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i4.Future<List<_i5.ProductItemModel>> getProducts({
    required int? page,
    required int? perPage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i4.Future<List<_i5.ProductItemModel>>.value(
            <_i5.ProductItemModel>[]),
      ) as _i4.Future<List<_i5.ProductItemModel>>);

  @override
  _i4.Future<List<_i5.ProductItemModel>> getProductsByCategory({
    required String? category,
    required int? page,
    required int? perPage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [],
          {
            #category: category,
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i4.Future<List<_i5.ProductItemModel>>.value(
            <_i5.ProductItemModel>[]),
      ) as _i4.Future<List<_i5.ProductItemModel>>);

  @override
  _i4.Future<List<_i6.SearchProductItemModel>> searchProducts(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [query],
        ),
        returnValue: _i4.Future<List<_i6.SearchProductItemModel>>.value(
            <_i6.SearchProductItemModel>[]),
      ) as _i4.Future<List<_i6.SearchProductItemModel>>);
}
